dynamic_record:
  adapter: mysql2
  database: dynamic_record_test_db
  username: stephenp 
  password: albany  
  host: localhost
  pool: 5
  timeout: 5000

dynamic_record_sqlite:
  adapter: sqlite3
  database: 'dynamic_record.sqlite3' 

dynamic_record_error_db:
  adapter: error_db
  database: nil

dynamic_record_postgres:
  adapter: postgres
  database: dynamic_record_test_db
