dynamic_record:
  adapter: mysql2
  database: dynamic_record_test_db
  username: stephenp 
  password: albany  
  host: localhost
  pool: 5
  timeout: 5000

dynamic_record_sqlite:
  adapter: sqlite3
  database: 'dynamic_record.sqlite3' 
