development:
  adapter: mysql2
  database: dynamic_record_test_db
  username: <%= ENV['db_user'] || 'stephenp' %>
  password: <%= ENV['db_pass'] || 'albany' %>
  host: localhost
  pool: 5
  timeout: 5000
